#!/usr/bin/env python3
"""
Static mapping of ASX Health Care sector company codes to company names.

This is a simplified version derived from `asx_healthcare_mapping.py`,
containing only:

    code -> company name
"""

HEALTHCARE_STOCKS = {
    "4DX": "4DMEDICAL Ltd",
    "ACR": "ACRUX Ltd",
    "AYA": "ARTRYA Ltd",
    "ACW": "Actinogen Medical Ltd",
    "1AD": "Adalta Ltd",
    "ADR": "Adherium Ltd",
    "AFP": "Aft Pharmaceuticals Ltd",
    "ALC": "Alcidion Group Ltd",
    "1AI": "Algorae Pharmaceuticals Ltd",
    "ATH": "Alterity Therapeutics Ltd",
    "AGH": "Althea Group Holdings Ltd",
    "ATX": "Amplia Therapeutics Ltd",
    "ANR": "Anatara Lifesciences Ltd",
    "ANN": "Ansell Ltd",
    "AVR": "Anteris Technologies Global Corp",
    "AHX": "Apiam Animal Health Ltd",
    "AGN": "Argenica Therapeutics Ltd",
    "RGT": "Argent Biopharma Ltd",
    "ARX": "Aroa Biosurgery Ltd",
    "ALA": "Arovella Therapeutics Ltd",
    "AT1": "Atomo Diagnostics Ltd",
    "AHC": "Austco Healthcare Ltd",
    "ACL": "Australian Clinical Labs Ltd",
    "AVE": "Avecho Biotechnology Ltd",
    "AVH": "Avita Medical Inc",
    "BOD": "BOD Science Ltd",
    "BP8": "BPH Global Ltd",
    "BDX": "Bcal Diagnostics Ltd",
    "BMT": "Beamtree Holdings Ltd",
    "BIT": "Biotron Ltd",
    "BB1": "Blinklab Ltd",
    "BOT": "Botanix Pharmaceuticals Ltd",
    "CSL": "CSL Ltd",
    "CMB": "Cambium Bio Ltd",
    "CAN": "Cann Group Ltd",
    "CTQ": "Careteq Ltd",
    "CHM": "Chimeric Therapeutics Ltd",
    "CU6": "Clarity Pharmaceuticals Ltd",
    "CSX": "Cleanspace Holdings Ltd",
    "COV": "Cleo Diagnostics Ltd",
    "CC5": "Clever Culture Systems Ltd",
    "CUV": "Clinuvel Pharmaceuticals Ltd",
    "COH": "Cochlear Ltd",
    "CGS": "Cogstate Ltd",
    "CMP": "Compumedics Ltd",
    "CQT": "Conneqt Health Ltd",
    "CBL": "Control Bionics Ltd",
    "CTE": "Cryosite Ltd",
    "CVB": "Curvebeam Ai Ltd",
    "CYC": "Cyclopharm Ltd",
    "CYP": "Cynata Therapeutics Ltd",
    "DXB": "Dimerix Ltd",
    "DOC": "Doctor Care Anywhere Group Plc",
    "DVL": "Dorsavi Ltd",
    "EBR": "EBR Systems Inc",
    "ECS": "ECS Botanics Holdings Ltd",
    "EZZ": "EZZ Life Science Holdings Ltd",
    "EBO": "Ebos Group Ltd",
    "EMV": "Emvision Medical Devices Ltd",
    "EMD": "Emyria Ltd",
    "ENL": "Enlitic Inc",
    "EPN": "Epsilon Healthcare Ltd",
    "FRE": "Firebrick Pharma Ltd",
    "FPH": "Fisher & Paykel Healthcare Corporation Ltd",
    "FCG": "Freedom Care Group Holdings Ltd",
    "GSS": "Genetic Signatures Ltd",
    "GTG": "Genetic Technologies Ltd",
    "GLH": "Global Health Ltd",
    "HIQ": "HITIQ Ltd",
    "HLS": "Healius Ltd",
    "HMD": "Heramed Ltd",
    "HXL": "Hexima Ltd",
    "IDT": "IDT Australia Ltd",
    "IXC": "INVEX Therapeutics Ltd",
    "IBX": "Imagion Biosystems Ltd",
    "IME": "Imexhs Ltd",
    "IMC": "Immuron Ltd",
    "IMM": "Immutep Ltd",
    "IPD": "Impedimed Ltd",
    "IMR": "Imricor Medical Systems Inc",
    "IMU": "Imugene Ltd",
    "IRX": "Inhalerx Ltd",
    "IIQ": "Inoviq Ltd",
    "IDX": "Integral Diagnostics Ltd",
    "ICR": "Intelicare Holdings Ltd",
    "IVX": "Invion Ltd",
    "ILA": "Island Pharmaceuticals Ltd",
    "LTP": "LTR Pharma Ltd",
    "LGP": "Little Green Pharma Ltd",
    "LDX": "Lumos Diagnostics Holdings Ltd",
    "M7T": "MACH7 Technologies Ltd",
    "MYX": "Mayne Pharma Group Ltd",
    "MDR": "Medadvisor Ltd",
    "MVP": "Medical Developments International Ltd",
    "MEM": "Memphasys Ltd",
    "MSB": "Mesoblast Ltd",
    "MX1": "Micro-X Ltd",
    "MAP": "Microba Life Sciences Ltd",
    "MVF": "Monash Ivf Group Ltd",
    "NC6": "Nanollose Ltd",
    "NAN": "Nanosonics Ltd",
    "NEU": "Neuren Pharmaceuticals Ltd",
    "NUZ": "Neurizon Therapeutics Ltd",
    "NSB": "Neuroscientific Biopharmaceuticals Ltd",
    "NTI": "Neurotech International Ltd",
    "NXN": "Nexsen Ltd",
    "NXS": "Next Science Ltd",
    "EYE": "Nova EYE Medical Ltd",
    "NOX": "Noxopharm Ltd",
    "NYR": "Nyrada Inc",
    "OCA": "Oceania Healthcare Ltd",
    "OSL": "Oncosil Medical Ltd",
    "ONE": "Oneview Healthcare Plc",
    "OPT": "Opthea Ltd",
    "OIL": "Optiscan Imaging Ltd",
    "OCC": "Orthocell Ltd",
    "OSX": "Osteopore Ltd",
    "PAB": "PATRYS Ltd",
    "PYC": "PYC Therapeutics Ltd",
    "PEB": "Pacific Edge Ltd",
    "PCK": "Painchek Ltd",
    "PAR": "Paradigm Biopharmaceuticals Ltd",
    "PGC": "Paragon Care Ltd",
    "PER": "Percheron Therapeutics Ltd",
    "PNV": "Polynovo Ltd",
    "PTX": "Prescient Therapeutics Ltd",
    "PME": "Pro Medicus Ltd",
    "PIQ": "Proteomics International Laboratories Ltd",
    "RHY": "RHYTHM Biosciences Ltd",
    "RAC": "Race Oncology Ltd",
    "RAD": "Radiopharm Theranostics Ltd",
    "RHC": "Ramsay Health Care Ltd",
    "RCE": "Recce Pharmaceuticals Ltd",
    "REG": "Regis Healthcare Ltd",
    "RNV": "Renerve Ltd",
    "RMD": "Resmed Inc",
    "RHT": "Resonance Health Ltd",
    "RYM": "Ryman Healthcare Ltd",
    "SDI": "SDI Ltd",
    "SIG": "Sigma Healthcare Ltd",
    "SHG": "Singular Health Group Ltd",
    "SOM": "Somnomed Ltd",
    "SHL": "Sonic Healthcare Ltd",
    "SPL": "Starpharma Holdings Ltd",
    "SNZ": "Summerset Group Holdings Ltd",
    "SNT": "Syntara Ltd",
    "TLX": "TELIX Pharmaceuticals Ltd",
    "TTX": "Tetratherix Ltd",
    "TRP": "Tissue Repair Ltd",
    "TRJ": "Trajan Group Holdings Ltd",
    "TRI": "Trivarx Ltd",
    "TRU": "Truscreen Group Ltd",
    "TYP": "Tryptamine Therapeutics Ltd",
    "UWC": "Underwood Capital Ltd",
    "UBI": "Universal Biosensors Inc",
    "UCM": "Uscom Ltd",
    "VBS": "Vectus Biosystems Ltd",
    "VFX": "Visionflex Group Ltd",
    "VLS": "Vita Life Sciences Ltd",
    "VHL": "Vitasora Health Ltd",
    "VFY": "Vitrafy Life Sciences Ltd",
    "VIT": "Vitura Health Ltd",
    "ZLD": "Zelira Therapeutics Ltd",
}


